"""Tablas de ventas

Revision ID: 57336f5b9881
Revises: e6ae7b30de34
Create Date: 2020-05-03 13:31:30.847488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57336f5b9881'
down_revision = 'e6ae7b30de34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sells',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('surname', sa.String(length=255), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sell_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sell_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sell_id'], ['sells.id'], ),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sell_products')
    op.drop_table('sells')
    # ### end Alembic commands ###
