"""empty message

Revision ID: c3525b340096
Revises: 369ed7f295b8
Create Date: 2020-03-07 10:00:16.667808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3525b340096'
down_revision = '369ed7f295b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('email_confirmed_at', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'email_confirmed_at')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
